config/routes.rb
Rails.application.routes.draw do
  resources :colaboradores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/colaborador.rb
class Colaborador < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colaboradores_controller.rb
class ColaboradoresController < ApplicationController
  before_action :set_colaborador, only: %i[ show edit update destroy ]

  # GET /colaboradores or /colaboradores.json
  def index
    @colaboradores = Colaborador.all
  end

  # GET /colaboradores/1 or /colaboradores/1.json
  def show
  end

  # GET /colaboradores/new
  def new
    @colaborador = Colaborador.new
  end

  # GET /colaboradores/1/edit
  def edit
  end

  # POST /colaboradores or /colaboradores.json
  def create
    @colaborador = Colaborador.new(colaborador_params)

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to colaborador_url(@colaborador), notice: "Colaborador was successfully created." }
        format.json { render :show, status: :created, location: @colaborador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaboradores/1 or /colaboradores/1.json
  def update
    respond_to do |format|
      if @colaborador.update(colaborador_params)
        format.html { redirect_to colaborador_url(@colaborador), notice: "Colaborador was successfully updated." }
        format.json { render :show, status: :ok, location: @colaborador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradores/1 or /colaboradores/1.json
  def destroy
    @colaborador.destroy

    respond_to do |format|
      format.html { redirect_to colaboradores_url, notice: "Colaborador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborador
      @colaborador = Colaborador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def colaborador_params
      params.require(:colaborador).permit(:nome, :cpf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colaboradores_helper.rb
module ColaboradoresHelper
end

app/views/colaboradores/_colaborador.html.erb
<div id="<%= dom_id colaborador %>">
  <p>
    <strong>Nome:</strong>
    <%= colaborador.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= colaborador.cpf %>
  </p>

</div>

app/views/colaboradores/_form.html.erb
<%= form_with(model: colaborador) do |form| %>
  <% if colaborador.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(colaborador.errors.count, "error") %> prohibited this colaborador from being saved:</h2>

      <ul>
        <% colaborador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/colaboradores/edit.html.erb
<h1>Editing colaborador</h1>

<%= render "form", colaborador: @colaborador %>

<br>

<div>
  <%= link_to "Show this colaborador", @colaborador %> |
  <%= link_to "Back to colaboradores", colaboradores_path %>
</div>

app/views/colaboradores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Colaboradores</h1>

<div id="colaboradores">
  <% @colaboradores.each do |colaborador| %>
    <%= render colaborador %>
    <p>
      <%= link_to "Show this colaborador", colaborador %>
    </p>
  <% end %>
</div>

<%= link_to "New colaborador", new_colaborador_path %>

app/views/colaboradores/new.html.erb
<h1>New colaborador</h1>

<%= render "form", colaborador: @colaborador %>

<br>

<div>
  <%= link_to "Back to colaboradores", colaboradores_path %>
</div>

app/views/colaboradores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @colaborador %>

<div>
  <%= link_to "Edit this colaborador", edit_colaborador_path(@colaborador) %> |
  <%= link_to "Back to colaboradores", colaboradores_path %>

  <%= button_to "Destroy this colaborador", @colaborador, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leilao</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>